Inspira.Blog.WebMvc3/Areas/Admin/Controllers/UserController.cs
/*
Copyright 2010 Inspira Tecnologia.
All Rights Reserved.

Contact: Thiago Alves <thiago.alves@inspira.com.br>

This file is part of Web.Generics

Web.Generics is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Web.Generics is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with Web.Generics.  If not, see <http://www.gnu.org/licenses/>.
*/

﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inspira.Blog.WebMvc3.Areas.Admin.Models;
using Web.Generics.UserInterface.Models;
using Web.Generics.DomainServices;
using Inspira.Blog.DomainServices;
using Inspira.Blog.DomainModel;
using Web.Generics.ApplicationServices.DataAccess;
using Web.Generics.Infrastructure.DataAccess.NHibernate;

namespace Inspira.Blog.WebMvc3.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        UserService userService;
        public UserController()
        {
            this.userService = new UserService();
        }

        public ActionResult List(UserViewModel viewModel)
        {
            var users = new GenericService<User>(new GenericRepository<User>(new NHibernateRepositoryContext())).Select(null, viewModel.MyGrid);

            viewModel.MyGrid.Columns = GridColumn.Create("Name", "Nome completo", "Salary", "Salário", "BirthDate", "Data de nascimento");
            viewModel.MyGrid.DataSource = users;
            viewModel.MyGrid.DataBind();

            var blogs = new GenericService<WebLog>(new GenericRepository<WebLog>(new NHibernateRepositoryContext())).Select(null, viewModel.MyGrid2);
            viewModel.MyGrid2.Columns = GridColumn.Create("Title", "Título", "Creator", "Criador", "CreatedAt", "Criado em");
            viewModel.MyGrid2.DataSource = blogs;
            viewModel.MyGrid2.DataBind();

            return View("List", viewModel);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        } 

        [HttpPost]
        public ActionResult Create(UserViewModel userViewModel)
        {
            var isViewValid = userViewModel.Validate();
            if (isViewValid)
            {
                return RedirectToAction("List");
            }
            else
            {
                ModelState.AddModelError("_FORM", "Opa! Deu erro!");
                return View();
            }
        }
        
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Inspira.Blog.WebMvc3/Areas/Admin/Controllers/WebLogController.cs
/*
Copyright 2010 Inspira Tecnologia.
All Rights Reserved.

Contact: Thiago Alves <thiago.alves@inspira.com.br>

This file is part of Web.Generics

Web.Generics is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Web.Generics is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with Web.Generics.  If not, see <http://www.gnu.org/licenses/>.
*/

﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inspira.Blog.WebMvc3.Areas.Admin.Models;
using Web.Generics.DomainServices;
using Inspira.Blog.DomainModel;
using Web.Generics.ApplicationServices.DataAccess;
using Web.Generics.Infrastructure.DataAccess.NHibernate;
using Web.Generics.UserInterface.Models;

namespace Inspira.Blog.WebMvc3.Areas.Admin.Controllers
{
    public class WebLogController : Controller
    {
        public GenericService<User> userService;
        public GenericService<WebLog> webLogService;

        public WebLogController(GenericService<User> userService, GenericService<WebLog> webLogService)
        {
            this.userService = userService;
            this.webLogService = webLogService;
        }

        public ActionResult List(WebLogViewModel viewModel)
        {
            var blogs = webLogService.Select(null, viewModel.WebLogGrid);

            viewModel.WebLogGrid.Columns = GridColumn.Create("Title", "Título", "Creator", "Criador", "CreatedAt", "Criado em");
            viewModel.WebLogGrid.DataSource = blogs;
            viewModel.WebLogGrid.DataBind();

            var users = userService.Select(null, viewModel.UserGrid);

            viewModel.UserGrid.Columns = GridColumn.Create("Name", "Nome completo", "Salary", "Salário", "BirthDate", "Data de nascimento");
            viewModel.UserGrid.DataSource = users;
            viewModel.UserGrid.DataBind();

            return View(viewModel);
        }
    }
}

Inspira.Blog.WebMvc3/Controllers/IdentityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inspira.Blog.WebMvc3.Models.Identity;
using Web.Generics.ApplicationServices.Identity;
using Inspira.Blog.DomainModel;

namespace Inspira.Blog.WebMvc3.Controllers
{
    public class IdentityController : Controller
    {
        private readonly IdentityService<User> identityService;
        public IdentityController(IdentityService<User> identityService)
        {
            this.identityService = identityService;
        }

        public ActionResult LogOn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogOn(LogOnModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            if (this.identityService.Validate(viewModel.Username, viewModel.Password))
            {
                // TODO: encapsulate this in a service (makes it easier to test up)
                System.Web.Security.FormsAuthentication.RedirectFromLoginPage(viewModel.Username, viewModel.RememberMe);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // invalid credentials
                ModelState.AddModelError("INVALID_CREDENTIALS", "");
                return View();
            }
        }

        public ActionResult LogOff()
        {
            System.Web.Security.FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(RegisterModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            User user = new User();
            user.Name = viewModel.Name;
            user.Username = viewModel.Username;
            user.Email = viewModel.Email;

            if (viewModel.Password != viewModel.ConfirmPassword)
            {
                ModelState.AddModelError("PASSWORD_AND_CONFIRM_DONT_MATCH", "");
            }
            else
            {
                var result = this.identityService.Register(user, u => u.Username, u => u.Email, u => u.Password, viewModel.Password);

                if (result == RegisterStatus.Success)
                {
                    // TODO: encapsulate this in a service
                    System.Web.Security.FormsAuthentication.RedirectFromLoginPage(user.Username, false); // user log on
                    return RedirectToAction("Index", "Home");
                }

                if (result == RegisterStatus.UsernameAlreadyExists)
                {
                    ModelState.AddModelError("USER_ALREADY_EXISTS", "");
                }

                if (result == RegisterStatus.EmailAlreadyExists)
                {
                    ModelState.AddModelError("EMAIL_ALREADY_EXISTS", "");
                }
            }

            return View(viewModel);
        }

        public ActionResult ForgetPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ForgetPassword(String usernameOrEmail)
        {
            var validationKey = this.identityService.GenerateValidationKey(usernameOrEmail);
            if (validationKey == null)
            {
                ModelState.AddModelError("USER_NOT_FOUND", "");
                return View();
            }
            return RedirectToAction("ValidateKey");
        }

        public ActionResult ValidateKey()
        {
            ValidateKeyModel viewModel = new ValidateKeyModel();
            viewModel.Key = Request["Key"];

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult ValidateKey(ValidateKeyModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            //custom validation
            if (viewModel.NewPassword != viewModel.Confirm)
            {
                ModelState.AddModelError("PASSAWORD_AND_CONFIRM_DONT_MACHT", "");
            }
            if (viewModel.Key == "123")
            {
                ModelState.AddModelError("INVALID_KEY", "");
            }

            //retorn of view
            if (ModelState.IsValid)
            {
                return View("ValidateKeySuccess");
            }
            else
            {
                return View(viewModel);
            }
        }

        public ActionResult ChangePassword()
        {
            ChangePassword viewModel = new ChangePassword();

            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePassword viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);
            
            if (viewModel.NewPassword != viewModel.ConfirmNewPassword)
            {
                ModelState.AddModelError("PASSAWORD_AND_CONFIRM_DONT_MACHT", "");                
            }
            else
            {
                var userName = User.Identity.Name;
                var result = this.identityService.ChangePassword(userName, viewModel.CurrentPassword, viewModel.NewPassword);
                
                if (result == PasswordChangeStatus.Success)
                {
                    return RedirectToAction("Index", "Home");
                }

                if (result == PasswordChangeStatus.InvalidCurrentPassword)
                {
                    ModelState.AddModelError("INVALID_CURRENT_PASSWORD", "");
                }

                if (result == PasswordChangeStatus.InvalidPassword)
                {
                    ModelState.AddModelError("INVALID_PASSWORD", "");
                }
            }

            return View(viewModel);
        }
    }
}

Inspira.Blog.WebMvc3/Views/Shared/_BasicLayout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>@View.Title</title>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" /> 
	<link rel="stylesheet" href="http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css" type="text/css" />
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.1/build/calendar/assets/skins/sam/calendar.css" />
	<link rel="stylesheet" href="@Url.Content("~/assets/css/yuiapp.css")" type="text/css" />
	<link rel="stylesheet" href="@Url.Content("~/assets/css/jquery-ui.css")" type="text/css" />
	<link id="theme" rel="stylesheet" href="@Url.Content("~/assets/css/structure.css")" type="text/css" />
</head>
<body class="rounded">
    <div id="doc">
		<!-- page body -->
        <div id="bd">
            <div id="yui-main">

			@RenderBody()

            </div>            
        </div>
		<!-- /page body -->		
		<!-- footer - copyright info -->
        <div id="ft">
            <p class="inner">Copyright &copy; 2010 Inspira Admin</p>
        </div>
		<!-- /footer - copyright info -->
    </div>

	@* yui *@
	@* <script type="text/javascript" src="http://yui.yahooapis.com/3.0.0pr2/build/yui/yui-min.js" type="text/javascript"></script> *@

	@* yui jquery / plugins *@
	@*
	<script type="text/javascript" src="@Url.Content("~/assets/js/mvc/jquery-1.4.1-vsdoc.js")"></script>
	*@

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script> 
	<script type="text/javascript">!window.jQuery && document.write('<script src="@Url.Content("~/assets/js/jquery-1.4.2.min.js")"><\/script>')</script>   
    
	@* TODO: usar minify *@
	<script type="text/javascript" src="@Url.Content("~/assets/js/plugins/jquery.maskedinput-1.2.2.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/assets/js/plugins/jquery.price_format.1.3.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/assets/js/custom/default-config.js")"></script>

	@* jQuery UI *@
	<script type="text/javascript" src="@Url.Content("~/assets/js/plugins/jquery-ui-1.8rc3.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/assets/js/plugins/jquery.ui.datepicker-pt-BR.js")"></script>

	@* TinyMCE *@
	<script type="text/javascript" src="@Url.Content("~/assets/js/TinyMCE/tiny_mce.js")"></script>

</body>
</html>

Inspira.Blog.WebMvc3/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>@View.Title</title>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" /> 
	<link rel="stylesheet" href="http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css" type="text/css" />
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.1/build/calendar/assets/skins/sam/calendar.css" />
	<link rel="stylesheet" href="@Url.Content("~/assets/css/yuiapp.css")" type="text/css" />
	<link rel="stylesheet" href="@Url.Content("~/assets/css/jquery-ui.css")" type="text/css" />
	<link id="theme" rel="stylesheet" href="@Url.Content("~/assets/css/structure.css")" type="text/css" />
</head>
<body class="rounded">
    <div id="doc3" class="yui-t6">		
		<!-- header -->
        <div id="hd">
            <h1>Inspira Blog - Front End</h1>
			<div id="navigation">
				<ul id="primary-navigation">
					<li><a href="#">Menu item 1</a></li>
					<li><a href="#">Menu item 2</a></li>
				</ul>
				<ul id="user-navigation">
					<li><a href="#">Profile</a></li>
					<li><a href="#">Settings</a></li>
					<li><a href="#">Logout</a></li>
					@Html.Partial("_LogOnPartial")
				</ul>
				<div class="clear"></div>
			</div>
        </div>
        <!-- /header -->

		@RenderBody()

		<!-- footer - copyright info --> 
		<div id="ft"> 
		    <p class="inner">Copyright &copy; 2010 Inspira Admin</p> 
		</div> 
		<!-- /footer - copyright info --> 
 
	</div> 
    
	@* yui *@
	@* <script src="http://yui.yahooapis.com/3.0.0pr2/build/yui/yui-min.js" type="text/javascript"></script> *@

	@* yui jquery / plugins *@
	@*
	<script src="@Url.Content("~/assets/js/mvc/jquery-1.4.1-vsdoc.js")">
	*@
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script> 
	<script>!window.jQuery && document.write('<script src="@Url.Content("~/assets/js/jquery-1.4.2.min.js")"><\/script>')</script>   
    
	@* TODO: usar minify *@
	<script src="@Url.Content("~/assets/js/plugins/jquery.maskedinput-1.2.2.min.js")"></script>
	<script src="@Url.Content("~/assets/js/plugins/jquery.price_format.1.3.js")"></script>
	<script src="@Url.Content("~/assets/js/custom/default-config.js")"></script>

	@* jQuery UI *@
	<script src="@Url.Content("~/assets/js/plugins/jquery-ui-1.8rc3.min.js")"></script>
	<script src="@Url.Content("~/assets/js/plugins/jquery.ui.datepicker-pt-BR.js")"></script>

	@* TinyMCE *@
	<script src="@Url.Content("~/assets/js/TinyMCE/tiny_mce.js")"></script>
</body>
</html>

Inspira.Blog.WebMvc3/Views/Shared/_Layout.default.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>@View.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>Inspira - Blog</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Users", "List", "User")</li>
                    <li>@Html.ActionLink("WebLogs", "List", "WebLog")</li>
					<li>@Html.ActionLink("Posts", "List", "Post")</li>
					<li>@Html.ActionLink("Comments", "List", "Comment")</li>
					<li>@Html.ActionLink("Tags", "List", "Tag")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

Inspira.Blog.WebMvc3/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Identity") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Identity") ]
}